# CircleCI 2.1 configuration file
# Maintainer: Otto Jolanki

# Defaults and functions
---
version: 2.1
defaults: &defaults
  docker:
    - image: cimg/base@sha256:d75b94c6eae6e660b6db36761709626b93cabe8c8da5b955bfbf7832257e4201
  working_directory: ~/ptools

machine_defaults: &machine_defaults
  machine:
    image: ubuntu-1604:202007-01
  working_directory: ~/ptools

commands:
  set_environment_variables:
    description: "Set env for docker pushes and test runs"
    steps:
      - run:
          command: |
            echo "export PTOOLS_DOCKER_IMAGE_TAG=encodedcc/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" >> ${BASH_ENV}
            echo "export CROMWELL=./cromwell-49.jar" >> ${BASH_ENV}
            echo "export WOMTOOL=./womtool-49.jar" >> ${BASH_ENV}
            source ${BASH_ENV}

  install_python_requirements:
    description: "Install test workflow requirements"
    steps:
      - run: pyenv global 3.7.8
      - run: pip install --upgrade pip
      - run: pip install -r test_requirements.txt

  download_file:
    description: "Download a file using wget"
    parameters:
      file_url:
        type: string
    steps:
      - run: wget <<parameters.file_url>>

  prepare_run_environment:
    description: "Get machine ready to run workflows"
    steps:
      - set_environment_variables
      - install_python_requirements
      - download_file:
          file_url: "https://github.com/broadinstitute/cromwell/releases/download/49/cromwell-49.jar"
      - download_file:
          file_url: "https://github.com/broadinstitute/cromwell/releases/download/49/womtool-49.jar"


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - set_environment_variables
      - run:
          name: build image
          command: |
            echo "pulling template!"
            docker pull encodedcc/ptools:template
            docker login -u=${DOCKERHUB_USER} -p=${DOCKERHUB_PASS}
            docker build --cache-from encodedcc/ptools:template \
                -t $PTOOLS_DOCKER_IMAGE_TAG .
            docker push $PTOOLS_DOCKER_IMAGE_TAG
            docker logout
          no_output_timeout: 30m

  push_template:
      <<: *defaults
      steps:
        - checkout
        - setup_remote_docker
        - set_environment_variables
        - run:
            command: |
              docker pull $PTOOLS_DOCKER_IMAGE_TAG
              docker login -u=${DOCKERHUB_USER} -p=${DOCKERHUB_PASS}
              docker tag $PTOOLS_DOCKER_IMAGE_TAG encodedcc/ptools:template
              docker push encodedcc/ptools:template
              docker logout
            no_output_timeout: 30m

# Workflow
workflows:
  build_workflow:
    jobs:
      - build
      - push_template:
          requires:
            - build 
